import {mock,test,expect,afterAll} from 'bun:test';
import {Pool} from 'pg';
import crypto from 'node:crypto';
const url=process.env.TEST_DATABASE_URL||'';
if(!url.includes('127.0.0.1:55439/speed_acceptance'))throw Error('Use the isolated local acceptance database');
const pool=new Pool({connectionString:url});
mock.module('../lib/core.js',()=>({pool,buyer:async(req:any)=>{if(!req.headers.authorization)throw Error('unauthorized');return{id:req.headers.authorization,email:'isolated@example.invalid'};},requireConfig:(name:string)=>{if(name==='CRM_CALLBACK_HOSTS')return 'fusiondataco.app';throw Error('not_configured');},callbackUrl:()=>{throw Error('external_receiver_disabled_in_test');},admin:()=>true}));
const demo=(await import('../api/demo')).default;
const account=(await import('../api/account')).default;
const deliver=(await import('../api/deliver')).default;
async function call(handler:any,user:string,method:string,body:any={},query:any={}){const r:any={code:200,headers:{},setHeader(k:string,v:string){this.headers[k]=v;},status(code:number){this.code=code;return this;},json(data:any){this.data=data;return this;},end(){return this;}};await handler({method,headers:{authorization:user},body,query},r);return r;}
afterAll(async()=>{await pool.query('TRUNCATE fs_demo_jobs,fs_account_security_events,fs_delivery_reviews,fs_jobs,fs_accounts,fs_tenants CASCADE');await pool.end();});
test('private demo persists replay safely and stays out of live queue',async()=>{const requestId=crypto.randomUUID();const body={requestId,notes:'A broken system needs urgent review today'};const a=await call(demo,'alice','POST',body);expect(a.code).toBe(201);const b=await call(demo,'alice','POST',body);expect(b.data.job.id).toBe(a.data.job.id);expect((await call(demo,'alice','POST',{...body,notes:'different'})).code).toBe(409);expect((await call(demo,'bob','GET')).data.jobs).toHaveLength(0);expect((await call(demo,'alice','GET')).data.jobs).toHaveLength(1);expect((await pool.query('SELECT count(*)::int AS n FROM fs_jobs')).rows[0].n).toBe(0);});
test('anonymous demo is denied',async()=>expect((await call(demo,'','GET')).code).toBe(401));
test('paid workspace configuration and inquiry persist without external sends',async()=>{await pool.query("INSERT INTO fs_accounts(buyer_id,email,billing_status,access_until) VALUES('paid-alice','isolated@example.invalid','active',now()+interval '1 day')");const setup=await call(account,'paid-alice','POST',{action:'configure',businessName:'Isolated acceptance workspace',deliveryMode:'workspace'});expect(setup.code).toBe(200);expect(setup.data.slug).toStartWith('buyer-');const requestId=crypto.randomUUID();const input={action:'submit_lead',notes:'Need to schedule a service',requestId};const a=await call(account,'paid-alice','POST',input);expect(a.code).toBe(202);expect((await call(account,'paid-alice','POST',input)).data.job.id).toBe(a.data.job.id);expect((await call(account,'other','POST',input)).code).toBe(400);const result=await call(deliver,'operator','POST');expect(result.data.status).toBe('ready_for_review');expect((await call(account,'other','GET')).data.jobs).toHaveLength(0);expect((await call(account,'paid-alice','GET')).data.jobs[0].delivery_status).toBe('ready_for_review');});
